---
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--config=pyproject.toml"]
        pass_filenames: true
        exclude: ontology-management-base/

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--settings=pyproject.toml"]
        pass_filenames: true
        exclude: ontology-management-base/

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--config=.flake8"]
        pass_filenames: true
        exclude: ontology-management-base/

      - id: jsonld-lint
        name: JSON-LD Linter
        entry: python ontology-management-base/src/jsonld_lint.py
        language: system
        types: [json]
        files: \.json$
        exclude: ontology-management-base/

      - id: turtle-lint
        name: Turtle Linter
        entry: python ontology-management-base/src/turtle_lint.py
        language: system
        types: [text]
        files: \.(ttl)$
        exclude: ontology-management-base/
